FROM ruby:3.3.8-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    curl \
    file \
    git \
    imagemagick \
    libcairo2-dev \
    libffi-dev \
    libgirepository1.0-dev \
    libglib2.0-dev \
    libmagickwand-dev \
    libpoppler-glib-dev \
    default-libmysqlclient-dev \
    musl-dev \
    nodejs \
    npm \
    openssh-client \
    pkg-config \
    libpq-dev \
    tini \
    tzdata \
    libyaml-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN gem install bundler:2.6.8
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

ENV RAILS_ENV=test
ENV RACK_ENV=test

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["bash"]
